language: python
python:
  - '3.4'
  - '3.5'
  - '3.6.5'

services:
  - redis-server

install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/serve.py"
  - export FLASK_ENV=development

script: flask test
