version: "3"
services:
  app:
    container_name: gdst_news
    build: .
    command: gunicorn -c gunicorn.py serve:app
    environment:
      - FLASK_APP=serve.py
    ports:
      - "5001:5000"
    volumes:
      - .:/var/www/gdst_news
    external_links:
        - "redis:redis_url"
